sed -i 's/<footer id="about" className="bg-zinc-900\/80 backdrop-blur-2xl border-t border-zinc-700\/50 text-white py-16 lg:py-24 relative z-10">/<footer id="about" className="scroll-spy-section bg-white\/50 backdrop-blur-2xl border-t border-white\/60 text-zinc-900 py-16 lg:py-24 relative z-10">/g' src/App.tsx
sed -i 's/<div className="w-10 h-10 bg-white\/20 backdrop-blur-md border border-white\/30 rounded-xl flex items-center justify-center text-white font-display text-xl tracking-wider shadow-sm">/<div className="w-10 h-10 bg-zinc-900\/80 backdrop-blur-md border border-zinc-700\/50 rounded-xl flex items-center justify-center text-white font-display text-xl tracking-wider shadow-sm">/g' src/App.tsx
sed -i 's/<p className="text-zinc-300 font-sans max-w-sm">/<p className="text-zinc-600 font-sans max-w-sm">/g' src/App.tsx
sed -i 's/<ul className="space-y-4 font-sans text-zinc-400">/<ul className="space-y-4 font-sans text-zinc-600">/g' src/App.tsx
sed -i 's/hover:text-white transition-colors/hover:text-zinc-900 transition-colors/g' src/App.tsx
sed -i 's/<p className="text-zinc-400 font-sans mb-4">Subscribe for the latest drops and exclusive offers.<\/p>/<p className="text-zinc-600 font-sans mb-4">Subscribe for the latest drops and exclusive offers.<\/p>/g' src/App.tsx
sed -i 's/className="bg-black\/20 backdrop-blur-md border border-white\/20 text-white px-4 py-3 w-full font-sans focus:outline-none focus:ring-1 focus:ring-white rounded-l-xl placeholder:text-zinc-500"/className="bg-white\/30 backdrop-blur-xl border border-white\/40 text-zinc-900 px-4 py-3 w-full font-sans focus:outline-none focus:ring-1 focus:ring-zinc-900\/20 focus:bg-white\/50 rounded-l-xl placeholder:text-zinc-500 transition-all"/g' src/App.tsx
sed -i 's/<button className="bg-white\/20 backdrop-blur-md border border-\[#777777\] border-l-0 text-white px-6 py-3 font-display uppercase hover:bg-white\/30 transition-colors rounded-r-xl">/<button className="bg-white\/50 backdrop-blur-md border border-white\/40 border-l-0 text-zinc-900 px-6 py-3 font-display uppercase hover:bg-white\/80 transition-colors rounded-r-xl">/g' src/App.tsx
sed -i 's/<div className="border-t border-zinc-700\/50 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-sm text-zinc-400 font-sans">/<div className="border-t border-white\/60 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-sm text-zinc-500 font-sans">/g' src/App.tsx

